### ISSUE TITLE
Information about maxInactivity value wrong

### ISSUE THREAD

**Issue by Maxdvlpr** [googlecast/cast-custom-receiver#15]
On row 549 in sample_media_receiver.html it says that appConfig.maxInactivity = 6000 will cause a timeout after 10 minutes.

Your documentation (https://developers.google.com/cast/docs/custom_receiver) says that the same value, 6000, will cause a timeout after 100 minutes.

I assume the latter is correct.

**Comment by entertailion** [comment]
Thanks. Fixed comment.
